spin_manifest_version = 2

[application]
name = "advent-of-spin-2024"
version = "0.1.0"
authors = ["Shalier Xia <shalierkx@gmail.com>"]
description = "wishlist"

[[trigger.http]]
route = "/..."
component = "app"

[component.app]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "index.html", destination = "/index.html" },{ source = "styles.css", destination = "/styles.css" },{ source = "main.js", destination = "/main.js" },{source="images/4.jpeg", destination="/images/4.jpeg"}]

[[trigger.http]]
route = "/api/wishlists"
component = "spin-key-value"

[component.spin-key-value]
source = "spin-key-value/target/wasm32-wasip1/release/spin_key_value.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.spin-key-value.build]
workdir = "spin-key-value"
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
