package local:magic;

world spin-http{
    record request {
        method: string,
        path: string,
        body: option<string>,
    }
    record response {
        status: u32,
        body: option<string>,
    }
}

world spin-key-value {
    import store: interface{
        open-default: func() -> store;
        get: func(key: string) -> option<string>;
        set: func(key: string, value: string);
        delete: func(key: string);
        exists: func(key: string) -> bool;
    }
}

world magic {
    include spin-http;
    include spin-key-value;

    record wishlist{
        name: string,
        items: list<string>,
    }
    record wishlistcollection{
        wishlists: list<wishlist>,
    }
    import handle-request: func(req: request) -> response;
}
